version: "3"

services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile-server
    volumes:
      - ./server/:/usr/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    depends_on:
      - db
    environment:
      - PORT=${SERVER_PORT}
  db:
    # root:
    # user: root
    # pwd: root
    container_name: db
    restart: unless-stopped
    image: mongo:4.2
    volumes:
      - ./database/data:/data/db
      - ./database/config:/etc/mongo
    ports:
      - ${DB_PORT}:27017
    command:
      - "--auth"
      - "-f"
      - "/etc/mongo/mongod.conf"
